### ISSUE TITLE
Automatic discovery of MQTT credentials

### ISSUE THREAD

**Issue by 1technophile** [mihsu81/addon-theengsgw#10]
Hello,

I see that this addon:
https://github.com/mdegat01/addon-amr2mqtt/tree/main/amr2mqtt

Doesn't need to enter broker host and MQTT credentials. Do you think we could leverage the same principle per default?
And only use the host and credentials if they are set by the user.

**Comment by mihsu81** [comment]
Good find. I doubt I'll have time to start working on it before mid-December though.

**Comment by 1technophile** [comment]
I suspect that we are only missing this:
https://github.com/mdegat01/addon-amr2mqtt/blob/8fdd816e98d74afd53aa2b958e38d86063c0af94/amr2mqtt/config.yaml#L18

here is the doc:
https://developers.home-assistant.io/docs/add-ons/configuration/

Thoughts?
I can do the modification and test.

**Comment by mihsu81** [comment]
I would say that ```- mqtt:want``` is not related, based on the documentation.
But try it if you want. I'm not an authority on the matter. 😁

**Comment by 1technophile** [comment]
I confirm that ` - mqtt:want` is not related.

**Comment by 1technophile** [comment]
Just found that the RTL_433 addon doesn't need MQTT credentials also https://github.com/pbkhrv/rtl_433-hass-addons/blob/main/rtl_433/config.json

**Comment by mihsu81** [comment]
Added in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.4.
Thanks for the hints.
