### ISSUE TITLE
Large number of identical messages flooding MQTT server

### ISSUE THREAD

**Issue by dpritt** [mihsu81/addon-theengsgw#15]
Just installed the gateway to pick up my LYWSD03MMC devices and I have noticed some messages flooding the MQTT gateway.
Running HA 2022.11.2 on a Odroid N2.
Monitoring the traffic using MQTTfx I get the multiple identical messages from the same device, I have counted over 25 identical messages within a few seconds.
i.e
{"name": "ATC_A14E82", "id": "A4:C1:38:A1:4E:82", "rssi": -67, "brand": "Xiaomi", "model": "LYWSD03MMC", "model_id": "LYWSD03MMC_ATC", "tempc": 19.5, "tempf": 67.1, "hum": 67, "batt": 79, "volt": 2.92}

Now multiply this by 8 devices.
 
Is there anyway to reduce the amount, I would be happy to only send a message to HA every 30 seconds, and if it is possible to suppress identical ones to reduce the load?

I have changed scanning interval to 120 to try to slow this down, which has helped, just need to stop duplicates.

Otherwise brilliant bit of code, works better than the default integration, which keeps stopping.

**Comment by 1technophile** [comment]
Hello,

If you reduce the scan duration does it help ?
![image](https://user-images.githubusercontent.com/12672732/202000229-1253ae17-ac8b-4ffb-ad41-51590ef0eb45.png)

**Comment by dpritt** [comment]
Florian,
 
This is running on a test environment so I can try various settings.
 
Lowering the scan window has helped reduce the noise, although I still get two messages from each device within the time frame.
 
I will monitor how this work.
 
My live system is running a Tasmota gateway BLE on a ESP32, this does not seem to duplicate messages and controls my heating system, but I would like to remove the ESP32 as this is another 'box' to maintain.
 
Regards
 
Dave

**Comment by mihsu81** [comment]
These issues, if still present should be opened in the TheengsGateway repo.
