### ISSUE TITLE
Can't install addon on Home Assistant OS

### ISSUE THREAD

**Issue by kanshinmv** [mihsu81/addon-theengsgw#16]
I get the following error:
`ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/007e7788_theengsgw/install - The command '/bin/bash -o pipefail -c apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends -y build-essential bluez python3-pip python3-dev && pip3 install --extra-index-url=https://www.piwheels.org/simple TheengsGateway==0.6.5' returned a non-zero code: 1`

**Home Assistant 2022.12.4**
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221212.0 - latest

_HAOS running inside proxmox vm_

**Comment by 1technophile** [comment]
Hello,

Do you have the possibility to run the commands separately to identify the one that fails ?

**Comment by kanshinmv** [comment]
No. I don't have access to 'apt', 'python' or 'pip' commands via SSH =(

**Comment by 1technophile** [comment]
Could you install the appliance on your Proxmox:
https://github.com/theengs/gateway-appliance
Or as a docker:
https://gateway.theengs.io/install/install.html#install-theengs-gateway-as-a-docker
And see if it works ?

**Comment by koenvervloesem** [comment]
I suspect it's related to this: https://github.com/theengs/gateway/pull/84

We need a new Theengs Gateway (and addon) release with this PR to remedy this.

**Comment by 1technophile** [comment]
Ok let's do a release

**Comment by kanshinmv** [comment]
1.3.2 installed without problems

**Comment by bcutter** [comment]
> 1.3.2 installed without problems

...so you wanna close this issue? :-)
