### ISSUE TITLE
Addon on Home Assistant OS fails to install

### ISSUE THREAD

**Issue by kelos-01** [mihsu81/addon-theengsgw#19]
**Failed to install add-on**
The command '/bin/bash -o pipefail -c apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends -y build-essential bluez python3-pip python3-dev && pip3 install --extra-index-url=https://www.piwheels.org/simple TheengsGateway==0.7.0' returned a non-zero code: 100

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0
HAOS barebone Raspberry Pi4/SSD

**Comment by 1technophile** [comment]
Hello,

Did you find a way to install it?

**Comment by kelos-01** [comment]
> Hello,
> 
> Did you find a way to install it?

Yes! - Rebooted the host and tired re-installing the addon. 
Additionally if more than one Bluetooth module, needs to be specified in the config. e.g hci0/hci1 etc.
