### ISSUE TITLE
ver 1.6.1 and TPMS sensors

### ISSUE THREAD

**Issue by stepir** [mihsu81/addon-theengsgw#24]
Hi

up until 1.5.0 my tpms sensors were recognized fine and very frequently.

Now only 1 sensor is recognized and updated only after x hours. If I do a BLE scan or use other applications for the same purpose, the sensors work fine.

How can I roll back version using HASSIO addons?

**Comment by 1technophile** [comment]
Hello,

Try to change the time between scans to a lower value like 1 second and see if it helps
![image](https://user-images.githubusercontent.com/12672732/230799454-693c6968-4fc4-43c7-90ef-53a365da0eb3.png)

**Comment by stepir** [comment]
Thanks! I tried playing a bit with both time_between and scan interval but wont change much. After many hours the sensors are discovered. I'm more than 24hrs I'm still missing 1 our of 6, plus the others are updated only after several hours and not every minute like what is happening with a BLE SCAN

**Comment by stepir** [comment]
anyone know how can I access the log file from cli? the portion exposed into HA ui is just flooded with apple device logs.

**Comment by stepir** [comment]
I don't know the addon slug https://community.home-assistant.io/t/where-are-the-hassio-addon-logs-stored/30060/11 but suspect I would get only the same output...

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/36472935/230864918-d2d8c1db-0f3d-4c95-aaca-28febe1d3906.png">


There is no sign of my tpms sensors in the logs - even in debug mode

**Comment by stepir** [comment]
this in less than 1 minutes

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/36472935/230880434-91f0d99a-71ae-48b0-a8bc-7f91e97f099f.png">

while in HA one sensor is never found:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/36472935/230880543-e78b42fb-6a60-4478-a4a2-17d6e3065718.png">

and update time 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/36472935/230880720-cca78a80-35af-4543-a8a8-ce17780d8ff1.png">

**Comment by stepir** [comment]
I realised the issue is the MQTT integration - which is not reading the correct updated values.

![image](https://user-images.githubusercontent.com/36472935/231825034-3f2712d5-c221-446e-ab0f-7efe4bba8e7d.png)

**Comment by stepir** [comment]
the issue is with the discovery feature - the sensors are constantly read by the gateway but the discovery topic is not being updated

**Comment by 1technophile** [comment]
the discovery topic is constant, it does not have to change. It represents the entity definition (parameters, names, device linked)

Do you see the sensor data changing on the broker while not changing into HA?

**Comment by stepir** [comment]
apologies for my English - the values inside the discovery topic `homeassistant/sensor` are not being updated, the values under `home/TheengsGateway/BTtoMQTT` are constantly updated

I disabled discovery and manually parsed and configured mqtt sensors as I was doing before the discovery feature was implemented and I have everything working now

**Comment by 1technophile** [comment]
No problem, my English is perfectible too

> I disabled discovery and manually parsed and configured mqtt sensors as I was doing before the discovery feature was implemented and I have everything working now

Glad to hear that it works

**Comment by stepir** [comment]
thanks for helping me and following the thread - for some reasons the gateway is not updating the values under discovery only of the TPMS

**Comment by 1technophile** [comment]
I'm not sure what the issue is, if you get a chance to connect to the broker with MQTT explorer, and could share the following:
* Discovery topic
* Discovery payload (the json message)


Any warning seen on Home Assistant logs

**Comment by stepir** [comment]
see this sensors has been updated every 2 mins:

![image](https://user-images.githubusercontent.com/36472935/231847978-1f33cd06-a06f-4856-9ad7-b3fc3bb4ab75.png)

While the same into the discovery topic only once:

![image](https://user-images.githubusercontent.com/36472935/231848236-80e89db8-61fe-4059-878b-d122875ec39e.png)


`{"stat_t": "+/+/BTtoMQTT/81EACA21BA00", "name": "TPMS-count", "uniq_id": "81EACA21BA00-count", "val_tpl": "{{ value_json.count | is_defined }}", "state_class": "measurement", "device": {"identifiers": ["81EACA21BA00"], "connections": [["mac", "81EACA21BA00"]], "manufacturer": "GENERIC", "model": "TPMS", "name": "TPMS2_21BA00", "via_device": "TheengsGateway"}}`

**Comment by 1technophile** [comment]
Strange, it looks good to me

**Comment by stepir** [comment]
and after 10 minutes under `home/TheengsGateway/BTtoMQTT` I have 14 updates

![image](https://user-images.githubusercontent.com/36472935/231850666-625c3036-110b-4a90-bb5b-97a149dbc931.png)

but under` homeassistant/sensor` only 1 still

![image](https://user-images.githubusercontent.com/36472935/231850590-1edfccab-1839-4e9f-a827-3f36762a22e2.png)

**Comment by stepir** [comment]
despite having `DISCOVERY: false` the gateway keep populating the `DISCOVERY_TOPIC: homeassistant/sensor`

I'm unsure what is happening here
