### ISSUE TITLE
Supervised HA Add-on failed to start

### ISSUE THREAD

**Issue by EinSchwerd** [mihsu81/addon-theengsgw#26]
Tha addon fails to start with the following log:

ERROR:BLEGateway:Failed to connect to MQTT broker localhost:1883 return code: 5
ERROR:BLEGateway:Disconnected with return code = 5

Running HA 2023.7.1 on Debian 12

Could you shed some details on what these error codes mean?
I tried to change the port to 1884 (web-socket) and the error code changed to 2 but the addon still did not start.

**Comment by 1technophile** [comment]
Error code 5 means unauthorized
https://www.vtscada.com/help/Content/D_Tags/D_MQTT_ErrMsg.htm

Either a wrong password, user name or both

**Comment by EinSchwerd** [comment]
I don't have a user/pass configured as I thought it works with the default HA user/pass just like Mosquitto and my other *toMQTT add-ons. 
Is there a way to make the add-on use the default ha user/pass?

**Comment by mihsu81** [comment]
Not yet implemented, but you're free to submit a PR with the needed changes.
