### ISSUE TITLE
TheengsGateway 1.8.0 on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by Takst3in** [mihsu81/addon-theengsgw#27]
Not sure why, but same version runs without issues on my VM host of HomeAssistant, but when setting it up pn a RPi3b+ for my garage, the AddOn fails, please advice.

Log from Supervisor:
23-08-12 20:27:10 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 007e7788/aarch64-addon-theengsgw with version 1.8.0
23-08-12 20:27:59 ERROR (SyncWorker_2) [supervisor.docker.manager] Container addon_007e7788_theengsgw is not running
23-08-12 20:30:28 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_007e7788_theengsgw application
23-08-12 20:30:28 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 007e7788/aarch64-addon-theengsgw with version 1.8.0

Log from AddOn:
[20:25:36] INFO: Creating TheengsGateway configuration...
[20:25:46] INFO: Starting TheengsGateway...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__init__.py", line 26, in <module>
    from .ble_gateway import run
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/ble_gateway.py", line 51, in <module>
    from bleak.backends.bluezdbus.advertisement_monitor import OrPattern
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/advertisement_monitor.py", line 12, in <module>
    from dbus_fast.service import ServiceInterface, dbus_property, method, PropertyAccess
  File "/usr/local/lib/python3.9/dist-packages/dbus_fast/__init__.py", line 1, in <module>
    from . import aio, glib, introspection, message_bus, proxy_object, service
  File "/usr/local/lib/python3.9/dist-packages/dbus_fast/aio/__init__.py", line 1, in <module>
    from .message_bus import MessageBus
  File "/usr/local/lib/python3.9/dist-packages/dbus_fast/aio/message_bus.py", line 9, in <module>
    from .. import introspection as intr
  File "/usr/local/lib/python3.9/dist-packages/dbus_fast/introspection.py", line 5, in <module>
    from .errors import InvalidIntrospectionError
  File "/usr/local/lib/python3.9/dist-packages/dbus_fast/errors.py", line 57, in <module>
    from .message import Message
  File "src/dbus_fast/message.py", line 1, in init dbus_fast.message
ValueError: dbus_fast._private.marshaller.Marshaller size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

**Comment by Takst3in** [comment]
I have not figured out what this was caused by, but the BLE Monitor integration does detect BLE devices via my RPi, when running Home Assistant on the RPi.
 
I today went ahead to install another OS on the RPi3b+, and installed TheengsGateway via "pip install TheengsGateway".

After setting it up with default (only host/port/user/password set) the PRi finally worked with your TheengsGateway, and relays this directly to my Home Assistant without any issues.

However, the goal here were to have my BM2 battery monitor to get into Home Assistant, this now updates, and i am able to get the "%" value of the monitor.

However, when using the app of the device, the device also can show specific value of "Volt", why is this information not showing thru TheengsGateway?

I would love to have this info here, but seems like I might have to convert % to V by some kind, If you do not have any magic that you can do.. 

I could possibly get you some logs/etc if needed, if you want to look further into this.

Thanks for the assistance, 
Best regards, Stian

**Comment by 1technophile** [comment]
Hello,

Thanks for sharing your journey. For information `volt` is only retrieved by OpenMQTTGateway with an esp32.
You can see on the information  exchanged by the BM2 in the Theengs portal that only `battery` is present.
Also for such use cases an esp32 may be more convenient in term of location setup,  range may be challenging due to the surrounding of metallic parts. The esp32 offers more flexibility of placement.

**Comment by Takst3in** [comment]
@1technophile Thanks for the info, I will give it another go with an ESP32 also, even tho I did not manage it to get working the other day with an ESP32.

What image should I choose for an ordinary ESP32 WROOM?

**Comment by 1technophile** [comment]
`esp32dev-ble` should work for your use case/board
https://docs.openmqttgateway.com/prerequisites/boards/esp32dev-ble.html

**Comment by Takst3in** [comment]
Hi @1technophile

You say "For information volt is only retrieved by OpenMQTTGateway with an esp32."

Is there any possibility to have the code ported to RPi3b+?

This cause i struggle with the range with esp32, and my RPi3b+ reads my battery state OK.

**Comment by 1technophile** [comment]
Hello,

From my experience, even if you can read the battery doesn't mean you will be able to handle a Bluetooth connection.

We are workig on integrating connections information to Theengs Decoder, so it is in progress.
