### ISSUE TITLE
Addon backup is huge (containing big mysterious image.tar - is this really needed?)

### ISSUE THREAD

**Issue by bcutter** [mihsu81/addon-theengsgw#28]
When HA creates a backup/snapshot of the TheengsGateway addon (v1.8.0) it contains next to few config JSON files also a `image.tar` with uncompressed ~ 500 MB of size.

I have no idea what it's content is important for (did no deep inspection so far), but: **the backup creation duration significantly increased** once TheengsGateway has been installed, also **backup size increased by a lot**.

Looking at what this addon does I don't understand why its backup has such a large footprint. Could you please
a) check if this is a bug / an accidental part of the backup
b) in case a is negative, if the `image.tar` is really needed

Depending on this I might exclude the addon from my full backup as currently the listed negative outcome outperforms the benefits (what we really need are just the addon settings, just a small json, right?).

**Comment by 1technophile** [comment]
I think the backup is taking the whole docker container instead of just the settings

**Comment by mihsu81** [comment]
@bcutter The size is expected because it's not a prebuilt image, like in most other cases.
I stopped using TheengsGateway for now because it was lacking some features I needed, like active connections. You can host a prebuilt image on your docker account and submit a PR to this Add-on, or create another one.

**Comment by bcutter** [comment]
Indeed it seems to compile/build after download (which is why it takes quite some time and is pretty stressful for the host).

I neither have a docker account nor walk on the dev side at all. 😀

Hopefully this will be improved. For me in case of a needed restore I could just download the sources (addon), re-install (build) and use the settings. I don't need the full image in every backup, that's completely unnecessary (but of course fulfills a "click restore, wait, it just works again" expectation/mindset).

**Comment by bcutter** [comment]
As it is marked as "solved" now:

I can only see an explanation why it is working the way it does currently. Wouldn't be a solution to provide pre-compiled images instead? I can't see any technical change/reaction on the described issue and completely don't understand why it has been closed (from someone not even using it... ;-) ).

**Comment by mihsu81** [comment]
It has been closed because I don't have any plans to host pre-built images. If you change your mind and want to contribute to the project, you're more than welcome.

**Comment by bcutter** [comment]
Well, that would have been nice to read instead of a plain "closed now" 😀 

---

_My own workaround is to not backup this addon at all, that's a complete waste of resources. Maybe manually every few weeks or automating it once a month. But I really think there could and should be a better solution for all users..._

---

While I'm not a dev, after doing an intensive 30 seconds research, I found the `backup_exclude` config option for addon backups at https://developers.home-assistant.io/docs/add-ons/configuration

Why don't we
- just use that for creating backups and
- let the image re-compile plus use the settings only for restores?
