### ISSUE TITLE
tls trusted certificates

### ISSUE THREAD

**Issue by Juliku** [mihsu81/addon-theengsgw#32]
Where do i need to put the ca certificates for tls?
Or is there an option to ignore self signed certificates?

**Comment by mihsu81** [comment]
I think you're supposed to enable ENABLE_TLS. Can't say for sure because I find TLS for MQTT overkill for my internal network.

**Comment by 1technophile** [comment]
We don't manage certs for now.

**Comment by mihsu81** [comment]
Closing because the issue should be opened in the Theengs Gateway repo https://github.com/theengs/gateway.

**Comment by mihsu81** [comment]
My bad. It has been added in TGW 1.5.0. I'll create a new release to add this option.

**Comment by mihsu81** [comment]
Support added in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.2
