### ISSUE TITLE
Add-on doesn't start

### ISSUE THREAD

**Issue by Lheriss** [mihsu81/addon-theengsgw#33]
Hi,
I just installed the new version of the add-on on my rpi4 running hass. Theengs doesn't start, and the log outputs what follows.
Anything I can do?
Thanks. Laurent

[21:57:28] INFO: Creating TheengsGateway configuration...
[21:57:33] INFO: IDENTITIES: 
[21:57:33] INFO: BINDKEYS: 
[21:57:33] INFO: Starting TheengsGateway...
Exception ignored in: <function Client.__del__ at 0x7fa7a89ee0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__main__.py", line 5, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__init__.py", line 55, in main
    run(configuration, config_path)
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/ble_gateway.py", line 648, in run
    gw.connect_mqtt()
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/ble_gateway.py", line 162, in connect_mqtt
    self.client = mqtt_client.Client()
TypeError: __init__() missing 1 required positional argument: 'callback_api_version'

**Comment by mihsu81** [comment]
Hi,
Did you specify your mqtt server IP and credentials?

**Comment by Lheriss** [comment]
And the debug log shows this : 
`# Theengs Gateway Diagnostics

## Package Versions

| Name               | Value  |
|--------------------|--------|
| Theengs Gateway    | 1.3.0  |
| Theengs Decoder    | 1.7.0  |
| Bleak              | 0.21.1 |
| Bluetooth Clocks   | 0.2.0  |
| Bluetooth Numbers  | 1.1.1  |
| Paho MQTT          | 2.0.0  |
| Bluetooth Adapters | 0.17.0 |

## Python

| Name           | Value               |
|----------------|---------------------|
| Version        | 3.9.2               |
| Implementation | CPython             |
| Compiler       | GCC 10.2.1 20210110 |
| Executable     | /usr/bin/python3    |

## Operating System

| Name         | Value                                       |
|--------------|---------------------------------------------|
| System       | Linux                                       |
| Release      | 6.1.63-haos-raspi                           |
| Version      | #1 SMP PREEMPT Mon Feb  5 11:43:32 UTC 2024 |
| Machine type | aarch64                                     |

## Configuration

File: /root/theengsgw.conf

```
{
    "adapter": "hci1",
    "bindkeys": {},
    "ble": 1,
    "ble_scan_time": 10,
    "ble_time_between_scans": 60,
    "discovery": "1",
    "discovery_device_name": "TheengsGateway",
    "discovery_filter": "[IBEACON,GAEN,MS-CDP,APPLE_CONT,APPLE_CONTAT,APPLE_CONTAT-device,H5055]",
    "discovery_topic": "homeassistant",
    "enable_tls": 0,
    "enable_websocket": 0,
    "hass_discovery": 1,
    "host": "172.28.8.111",
    "identities": {},
    "log_level": "DEBUG",
    "lwt_topic": "home/TheengsGateway/LWT",
    "pass": "***",
    "port": 1883,
    "presence": 1,
    "presence_topic": "home/presence/TheengsGateway",
    "publish_advdata": 0,
    "publish_all": 1,
    "publish_topic": "home/TheengsGateway/BTtoMQTT",
    "scanning_mode": "active",
    "subscribe_topic": "home/+/BTtoMQTT/undecoded",
    "time_format": "0",
    "time_sync": [],
    "tracker_timeout": 120,
    "user": "***"
}
```

## Bluetooth adapters

Default adapter: hci0

### hci0

| Name         | Value                    |
|--------------|--------------------------|
| address      | DC:A6:32:XX:XX:XX        |
| sw_version   | HomeAssistantRPi4 #1     |
| hw_version   | usb:v1D6Bp0246d0546      |
| passive_scan | True                     |
| manufacturer | Raspberry Pi Trading Ltd |
| product      | None                     |
| vendor_id    | None                     |
| product_id   | None                     |

### hci1

| Name         | Value                   |
|--------------|-------------------------|
| address      | 00:01:95:XX:XX:XX       |
| sw_version   | HomeAssistantRPi4       |
| hw_version   | usb:v1D6Bp0246d0546     |
| passive_scan | True                    |
| manufacturer | Sena Technologies, Inc. |
| product      | 0001                    |
| vendor_id    | 0a12                    |
| product_id   | 0001                    |`

**Comment by Lheriss** [comment]
To answer : yes, MQTT server IP, user and password specified, too...

**Comment by Lheriss** [comment]
After some research, this could have to do with Paho MQTT | 2.0.0 :

https://github.com/eclipse/paho.mqtt.python/issues/814

**Comment by 1technophile** [comment]
I'm going to update the addon, hopefully this week. This will fix the issue

**Comment by Lheriss** [comment]
Nice, thanks!

**Comment by 1technophile** [comment]
Addon updated

**Comment by Lheriss** [comment]
Many thanks, it works!
