### ISSUE TITLE
Addon doesn't start on rpi3 with haos

### ISSUE THREAD

**Issue by Lheriss** [mihsu81/addon-theengsgw#34]
Hi,

I've got an issue : when trying to start the add-on on my rpi3 with hasos, I get this message :

Image 007e7788/aarch64-addon-theengsgw:1.11.0 does not exist for addon_007e7788_theengsgw

Here is the message :

<img width="1373" alt="Capture d’écran 2024-03-03 à 19 43 39" src="https://github.com/mihsu81/addon-theengsgw/assets/3762221/5c4f2515-3dd6-4786-98ed-978eb77cca3d">

I tried to rebuild the add-on, without success...

Thanks!

**Comment by mihsu81** [comment]
That's awkward. RPi3 is armv7, not aarch64. Can you share more details on this?

**Comment by Lheriss** [comment]
Hi,
It has been a while, and I solved it, probably by reinstalling the whole rpi. Don't know how and why the problem initially happened...
But I have a new problem with the latest version. I'll open a new issue.
