### ISSUE TITLE
release 1.5.0

### ISSUE THREAD

**Issue by xavax59** [mihsu81/addon-theengsgw#35]
Hello,

I would like to know how to update the add-on to version 1.5.0 in Home Assistant. Are there any specific instructions or documentation to follow for this update? 
https://github.com/theengs/gateway/releases

Thank you in advance for your help!

Best regards,

**Comment by mihsu81** [comment]
Added in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.1.
