### ISSUE TITLE
since last update to Current version 1.11.2 switchbot  outdoor meter doesn't shoe any temperature and humidity 

### ISSUE THREAD

**Issue by mktat81** [mihsu81/addon-theengsgw#37]
as mentioned in title since last update to Current version 1.11.2 switchbot  outdoor meter doesn't shoe any temperature and humidity

i do not receive  any errors in Log so i don't know how i can assist in finding the issue 
instead of the Temperature i receive "unknown" (same for Humidity)

**Comment by de0rc** [comment]
Same here, when using MQTT Explorer, it doesnt show any data from the gateway besides the LWT = online/offline. After downgrading back to 1.11.0, it started working fine again.

**Comment by martinpelant** [comment]
How do you downgrade?

**Comment by martinpelant** [comment]
Logs always show
INFO:BLEGateway:Sent 0 messages to MQTT even if it found devices

**Comment by 1technophile** [comment]
Even if you have the discovery filter set to `[IBEACON]` ?

**Comment by martinpelant** [comment]
Yes
![Screenshot_20240817_231436_Home Assistant](https://github.com/user-attachments/assets/0d866209-7f6a-4353-a6d5-b8e0b9515ca0)
![Screenshot_20240817_231136_Home Assistant](https://github.com/user-attachments/assets/d9b9db03-636c-4070-b451-876a6fc8950f)

**Comment by mihsu81** [comment]
The issue has been fixed in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.3
