### ISSUE TITLE
After Update [1.11.4] no information is sent to broker

### ISSUE THREAD

**Issue by chris777c** [mihsu81/addon-theengsgw#38]
Hello,

After updated at 1.11 to 1.11.4, I lost information sent to broker, when I restore to 1.11, all work great .

What do you do to cause this effect ?

System : PROXMOX 8.2.4
HAOS : 
 Core 2024.8.3
Supervisor 2024.09.1
Operating System 13.1
user interface 20240809.0

**Comment by mihsu81** [comment]
This is a bug in TheengsGateway 1.5.0, caused by specifying more than 1 entry in Discovery Filters. Specify only 1 or none and it will work fine.

**Comment by chris777c** [comment]
Hello,

Thank you for reply but I have only one entry |IBEACON] on field Discover Filter . I try delete filed but appear again after save.
